title = "skysoup"
baseURL = "https://www.skysoup.design/"
theme = "skysoup"

SectionPagesMenu = "main"

[[menu.main]]
name = "Home"
weight = 1
identifier = "/"
url = "/"

[[menu.main]]
name = "Articles"
weight = 2
identifier = "post"
url = "/post/"

[[menu.main]]
name = "About"
weight = 3
identifier = "about"
url = "/about/"

